# Generated by Django 4.2.11 on 2024-04-06 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
    ]
